/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mttprojects.program;

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;
import static utils.ToolsClass.*;

/**
 *
 * @author matiw
 */
public class CalculatorInternalFrame extends javax.swing.JInternalFrame {

    ArrayList<String> history = new ArrayList<String>();
    String history2 = "";
    float currentValue = 0;
    float preValue = 0;
    String valueOnScreen = "";
    boolean ShowResult = false;
    boolean hasDot = false;
    boolean getNewVal = true;
    String lastOperation = "";

    /**
     * Creates new form Calculator
     */
    public CalculatorInternalFrame() {
        initComponents();
        //SetDarkMode(this);

        ActionListener numButtonListener = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JButton button = (JButton) e.getSource();
                String value = button.getText();
                printLog("Click value: " + value);
                AddToCurrent(value);
            }
        };

        ActionListener operatorListener = new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                JButton button = (JButton) e.getSource();
                String value = button.getText();

                printLog("Click Operator: " + value);
                if(ShowResult)
                {
                    history2 = "";
                }
                if (!getNewVal) {
                    
                    lastOperation = value;
                    history.add(CheckValues());
                    history.add(value);
                    history2 += CheckValues();
                    history2 += value;

                    valueOnScreen = calculate() + "";
                    valueOnScreen = CheckValues();
                    updateScreen();
                    getNewVal = true;
                    TXT_history.setText(history2);
                }
            }
        };

        Component[] components = this.getContentPane().getComponents();
        for (Component component : components) {
            if (component instanceof JButton) {
                JButton button = (JButton) component;
                String accessibleName = button.getAccessibleContext().getAccessibleName();
                if (accessibleName != null) {
                    if (accessibleName.equals("NumButton")) {
                        button.addActionListener(numButtonListener);
                    } else if (accessibleName.equals("Operators")) {
                        button.addActionListener(operatorListener);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton NumberButtonParent = new javax.swing.JButton();
        BT_9 = new javax.swing.JButton();
        BT_8 = new javax.swing.JButton();
        BT_7 = new javax.swing.JButton();
        BT_6 = new javax.swing.JButton();
        BT_5 = new javax.swing.JButton();
        BT_4 = new javax.swing.JButton();
        BT_3 = new javax.swing.JButton();
        BT_2 = new javax.swing.JButton();
        BT_1 = new javax.swing.JButton();
        BT_0 = new javax.swing.JButton();
        BT_dot = new javax.swing.JButton();
        BT_equals = new javax.swing.JButton();
        BT_minus = new javax.swing.JButton();
        BT_add = new javax.swing.JButton();
        BT_divide = new javax.swing.JButton();
        BT_mult = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TXT_history = new javax.swing.JLabel();
        TXT_display = new javax.swing.JTextField();
        BT_clearEvery = new javax.swing.JButton();

        NumberButtonParent.setText("jButton1");
        NumberButtonParent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NumberButtonParentMouseClicked(evt);
            }
        });
        NumberButtonParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberButtonParentActionPerformed(evt);
            }
        });

        setClosable(true);
        setForeground(java.awt.Color.pink);
        setIconifiable(true);
        setTitle("Calculator");
        setToolTipText("");

        BT_9.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_9.setText("9");
        BT_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_9.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_9.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_9.setPreferredSize(new java.awt.Dimension(75, 75));

        BT_8.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_8.setText("8");
        BT_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_8.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_8.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_8.setPreferredSize(new java.awt.Dimension(75, 75));

        BT_7.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_7.setText("7");
        BT_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_7.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_7.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_7.setPreferredSize(new java.awt.Dimension(75, 75));

        BT_6.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_6.setText("6");
        BT_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_6.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_6.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_6.setPreferredSize(new java.awt.Dimension(75, 75));

        BT_5.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_5.setText("5");
        BT_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_5.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_5.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_5.setPreferredSize(new java.awt.Dimension(75, 75));

        BT_4.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_4.setText("4");
        BT_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_4.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_4.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_4.setPreferredSize(new java.awt.Dimension(75, 75));

        BT_3.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_3.setText("3");
        BT_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_3.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_3.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_3.setPreferredSize(new java.awt.Dimension(75, 75));
        BT_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numButtonClick(evt);
            }
        });

        BT_2.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_2.setText("2");
        BT_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_2.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_2.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_2.setPreferredSize(new java.awt.Dimension(75, 75));

        BT_1.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_1.setText("1");
        BT_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_1.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_1.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_1.setPreferredSize(new java.awt.Dimension(75, 75));

        BT_0.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_0.setText("0");
        BT_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_0.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_0.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_0.setPreferredSize(new java.awt.Dimension(75, 75));

        BT_dot.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_dot.setText(".");
        BT_dot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_dot.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_dot.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_dot.setPreferredSize(new java.awt.Dimension(75, 75));

        BT_equals.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_equals.setText("=");
        BT_equals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_equals.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_equals.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_equals.setPreferredSize(new java.awt.Dimension(75, 75));
        BT_equals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_equalsMouseClicked(evt);
            }
        });
        BT_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_equalsActionPerformed(evt);
            }
        });

        BT_minus.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_minus.setText("-");
        BT_minus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_minus.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_minus.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_minus.setPreferredSize(new java.awt.Dimension(75, 75));
        BT_minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_minusMouseClicked(evt);
            }
        });

        BT_add.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_add.setText("+");
        BT_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_add.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_add.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_add.setPreferredSize(new java.awt.Dimension(75, 75));
        BT_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_addMouseClicked(evt);
            }
        });
        BT_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_addActionPerformed(evt);
            }
        });

        BT_divide.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_divide.setText("÷");
        BT_divide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_divide.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_divide.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_divide.setPreferredSize(new java.awt.Dimension(75, 75));

        BT_mult.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_mult.setText("x");
        BT_mult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_mult.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_mult.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_mult.setPreferredSize(new java.awt.Dimension(75, 75));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TXT_history.setBackground(new java.awt.Color(51, 51, 51));
        TXT_history.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        TXT_history.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TXT_history.setToolTipText("");

        TXT_display.setEditable(false);
        TXT_display.setBackground(new java.awt.Color(102, 102, 102));
        TXT_display.setFont(new java.awt.Font("Consolas", 0, 50)); // NOI18N
        TXT_display.setForeground(new java.awt.Color(204, 204, 204));
        TXT_display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TXT_display.setText("0");
        TXT_display.setBorder(null);
        TXT_display.setCaretColor(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXT_history, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXT_display))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TXT_history, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(TXT_display, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BT_clearEvery.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        BT_clearEvery.setText("CE");
        BT_clearEvery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BT_clearEvery.setMaximumSize(new java.awt.Dimension(75, 75));
        BT_clearEvery.setMinimumSize(new java.awt.Dimension(75, 75));
        BT_clearEvery.setPreferredSize(new java.awt.Dimension(75, 75));
        BT_clearEvery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_clearEveryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT_clearEvery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BT_0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(BT_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BT_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BT_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BT_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BT_minus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BT_divide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BT_mult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BT_dot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BT_equals, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BT_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_clearEvery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BT_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BT_dot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BT_equals, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BT_mult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BT_divide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BT_minus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BT_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11))
        );

        BT_9.getAccessibleContext().setAccessibleName("NumButton");
        BT_9.getAccessibleContext().setAccessibleDescription("numbt");
        BT_8.getAccessibleContext().setAccessibleName("NumButton");
        BT_8.getAccessibleContext().setAccessibleDescription("numbt");
        BT_7.getAccessibleContext().setAccessibleName("NumButton");
        BT_7.getAccessibleContext().setAccessibleDescription("numbt");
        BT_6.getAccessibleContext().setAccessibleName("NumButton");
        BT_6.getAccessibleContext().setAccessibleDescription("numbt");
        BT_5.getAccessibleContext().setAccessibleName("NumButton");
        BT_5.getAccessibleContext().setAccessibleDescription("numbt");
        BT_4.getAccessibleContext().setAccessibleName("NumButton");
        BT_4.getAccessibleContext().setAccessibleDescription("numbt");
        BT_3.getAccessibleContext().setAccessibleName("NumButton");
        BT_3.getAccessibleContext().setAccessibleDescription("numbt");
        BT_2.getAccessibleContext().setAccessibleName("NumButton");
        BT_2.getAccessibleContext().setAccessibleDescription("numbt");
        BT_1.getAccessibleContext().setAccessibleName("NumButton");
        BT_1.getAccessibleContext().setAccessibleDescription("numbt");
        BT_0.getAccessibleContext().setAccessibleName("NumButton");
        BT_0.getAccessibleContext().setAccessibleDescription("numbt");
        BT_0.getAccessibleContext().setAccessibleParent(BT_0);
        BT_dot.getAccessibleContext().setAccessibleName("NumButton");
        BT_dot.getAccessibleContext().setAccessibleDescription("numbt");
        BT_dot.getAccessibleContext().setAccessibleParent(BT_0);
        BT_minus.getAccessibleContext().setAccessibleName("Operators");
        BT_add.getAccessibleContext().setAccessibleName("Operators");
        BT_divide.getAccessibleContext().setAccessibleName("Operators");
        BT_mult.getAccessibleContext().setAccessibleName("Operators");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_equalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_equalsActionPerformed

    private void numButtonClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numButtonClick

    }//GEN-LAST:event_numButtonClick

    private void NumberButtonParentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumberButtonParentMouseClicked

    }//GEN-LAST:event_NumberButtonParentMouseClicked

    public void AddToCurrent(String c) {
        if (c == ".") {
            hasDot = true;
        }
        if (getNewVal || ShowResult) {
            valueOnScreen = "";
            updateScreen();
            getNewVal = false;
            ShowResult = false;
        }

        valueOnScreen += c;
        updateScreen();
    }
    private void NumberButtonParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberButtonParentActionPerformed
        JButton button = (JButton) evt.getSource();
        String label = button.getLabel(); //Deprecated
        String label2 = button.getText();
        printLog(label);
        printLog(label2);
    }//GEN-LAST:event_NumberButtonParentActionPerformed

    private void BT_equalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_equalsMouseClicked
        if (!ShowResult) {

            history2 += CheckValues();
            valueOnScreen = calculate() + "";
            valueOnScreen = CheckValues();
            currentValue = 0;
            updateScreen();
            ShowResult = true;
            TXT_history.setText(history2 + "=");
            lastOperation = "=";
            getNewVal = false;
        }
    }//GEN-LAST:event_BT_equalsMouseClicked

    private void BT_minusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_minusMouseClicked

    }//GEN-LAST:event_BT_minusMouseClicked

    private void BT_clearEveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_clearEveryMouseClicked
        Reset();
    }//GEN-LAST:event_BT_clearEveryMouseClicked

    private void BT_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_addActionPerformed

    private void BT_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_addMouseClicked
    }//GEN-LAST:event_BT_addMouseClicked

    void updateScreen() {
        TXT_display.setText(valueOnScreen);
    }

    void Error() {
        valueOnScreen = "Syntax Error";
        ShowResult = true;
        updateScreen();
    }

    public void Reset() {
        currentValue = 0;
        preValue = 0;
        history.clear();
        valueOnScreen = "";
        TXT_display.setText("0");
        hasDot = false;
        ShowResult = false;
        history2 = "";
        TXT_history.setText(history2);
    }

    public String CheckValues() {
        try {
            float number = Float.parseFloat(valueOnScreen);
            int intValue = (int) number;
            if (intValue == number) {
                int intNumber = (int) number;
                return intNumber + "";
            } else {
                return number + "";
            }
        } catch (NumberFormatException e) {
            return "Syntax Error";
        }
    }

    public float calculate() {
        
        if(!ShowResult)
        {
        currentValue = myParseFloat(valueOnScreen);
        printLog("invoke calculate\n previous = " + preValue + "\nCurrentVal = " + currentValue + "\nWith operator: " + lastOperation);
        float result;
        switch (lastOperation) {

            case "+":
                result = preValue + currentValue;
                break;
            case "-":
                result = preValue - currentValue;
                break;
            case "x":
                result = preValue * currentValue;
                break;
            case "÷":
                result = preValue / currentValue;
                break;
            default:
                result = currentValue;
                break;

        }
        printLog("result = " + result);

        if (preValue == 0) {
            preValue = currentValue;
            return currentValue;
        } else {
            preValue = result;
            return result;
        }
        }
        else
            return preValue;
    }

    public Float myParseFloat(String str) {
        try {
            float number = Float.parseFloat(str);
            return number;
        } catch (NumberFormatException e) {
            Error();
            return 0.0f;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BT_0;
    public javax.swing.JButton BT_1;
    public javax.swing.JButton BT_2;
    public javax.swing.JButton BT_3;
    public javax.swing.JButton BT_4;
    public javax.swing.JButton BT_5;
    public javax.swing.JButton BT_6;
    public javax.swing.JButton BT_7;
    public javax.swing.JButton BT_8;
    public javax.swing.JButton BT_9;
    private javax.swing.JButton BT_add;
    private javax.swing.JButton BT_clearEvery;
    private javax.swing.JButton BT_divide;
    public javax.swing.JButton BT_dot;
    private javax.swing.JButton BT_equals;
    private javax.swing.JButton BT_minus;
    private javax.swing.JButton BT_mult;
    private javax.swing.JTextField TXT_display;
    private javax.swing.JLabel TXT_history;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
