/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mttprojects.program;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import static utils.ToolsClass.*;
/**
 *
 * @author matiw
 */
public class ProgramFrame extends javax.swing.JFrame {

    public static ProgramFrame instance;
    /**
     * Creates new form ProgramFrame
     */
    private BufferedImage img;

    public ProgramFrame() {
        instance = this;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        try {
            img = ImageIO.read(new URL("https://i.imgur.com/b4KqiKy.png"));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        deskPanel = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics grphcs) {
                super.paintComponent(grphcs);
                int x = (getWidth() - img.getWidth())/2;
                int y = (getHeight() - img.getHeight())/2;
                grphcs.drawImage(img, x, y, null);
            }
            /*
            @Override
            public Dimension getPreferredSize() {
                return new Dimension(img.getWidth(), img.getHeight());
            }*/
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newBT = new javax.swing.JMenuItem();
        OpenBT = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CopyBT = new javax.swing.JMenuItem();
        PasteBT = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout deskPanelLayout = new javax.swing.GroupLayout(deskPanel);
        deskPanel.setLayout(deskPanelLayout);
        deskPanelLayout.setHorizontalGroup(
            deskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        deskPanelLayout.setVerticalGroup(
            deskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 25));

        jMenu1.setText("Aplicaciones");

        newBT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        newBT.setText("Calculadora");
        newBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBTActionPerformed(evt);
            }
        });
        jMenu1.add(newBT);

        OpenBT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        OpenBT.setText("Contactos");
        OpenBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenBTActionPerformed(evt);
            }
        });
        jMenu1.add(OpenBT);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Juegos");

        CopyBT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CopyBT.setText("Buscaminas");
        CopyBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyBTActionPerformed(evt);
            }
        });
        jMenu2.add(CopyBT);

        PasteBT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        PasteBT.setText("SpaceShip");
        PasteBT.setToolTipText("");
        PasteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasteBTActionPerformed(evt);
            }
        });
        jMenu2.add(PasteBT);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPanel)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OpenBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenBTActionPerformed
        printLog("Open button pressed!");
        ContactsInternalFrame conFrame = new ContactsInternalFrame();
        this.add(conFrame);
        deskPanel.add(conFrame);
        conFrame.setVisible(true);
    }//GEN-LAST:event_OpenBTActionPerformed

    private void newBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBTActionPerformed
        printLog("New button pressed!");
        CalculatorInternalFrame calcFrame = new CalculatorInternalFrame();
        this.add(calcFrame);
        deskPanel.add(calcFrame);
        calcFrame.setVisible(true);
    }//GEN-LAST:event_newBTActionPerformed

    private void CopyBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyBTActionPerformed
        MineSweeper mineGame = new MineSweeper(deskPanel);
        this.add(mineGame);
        deskPanel.add(mineGame);
        mineGame.setVisible(true);
    }//GEN-LAST:event_CopyBTActionPerformed

    private void PasteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasteBTActionPerformed
        Tamagotchi tamachotchiGame = new Tamagotchi();
        this.add(tamachotchiGame);
        deskPanel.add(tamachotchiGame);
        tamachotchiGame.setVisible(true);
    }//GEN-LAST:event_PasteBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramFrame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CopyBT;
    private javax.swing.JMenuItem OpenBT;
    private javax.swing.JMenuItem PasteBT;
    public javax.swing.JDesktopPane deskPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem newBT;
    // End of variables declaration//GEN-END:variables
    
    private void changeBackground(JDesktopPane deskPanel, String imageUrl) {
  try {
    URL url = new URL(imageUrl);
    Image image = ImageIO.read(url);

    deskPanel.setBorder(BorderFactory.createEmptyBorder());
    deskPanel.setLayout(new BorderLayout());
    JLabel background = new JLabel(new ImageIcon(image));
    deskPanel.add(background, BorderLayout.CENTER);
    background.setSize(deskPanel.getSize());
  } catch (IOException ex) {
    ex.printStackTrace();
  }
}
}
